create table etelek(
etelid int auto_increment primary key,
nev varchar(100) not null,
leiras text not null,
elkeszitesiido int not null,
besorolas char(1)  not null
);

create table alapanyagok(
anyagid int auto_increment primary key,
nev varchar(30) not null,
mennyegyseg varchar(20) not null
);

create table hozzavalok(
id int auto_increment primary key,
etelid int not null,
anyagid int not null,
mennyiseg int not null,
foreign key (etelid) references etelek(etelid),
foreign key (anyagid) references alapanyagok(anyagid)
);

-- alapanyagok tábla adatai
insert into alapanyagok(nev,mennyegyseg) values
('olaj','ml'),
('paradicsomlé','ml'),
('paradicsompüré','gramm'),
('liszt','gramm'),
('só','csipet'),
('cukor','gramm'),
('bors','csipet'),
('víz','ml'),
('betűtészta','gramm'),
('zöldborsó','gramm'),
('sárgarépa','szál'),
('fehérrépa','szál'),
('zeller','gramm'),
('petrezselyem','csomó'),
('tej','ml'),
('rízs','gramm'),
('vaníliás cukor','csomag'),
('vaj','gramm'),
('fokhagyma','gerezd'),
('kakukkfű','kávéskanál'),
('hagyma','fej'),
('csirkemell filé','gramm'),
('mexikói zöldségkeverék','gramm'),
('tojás','db'),
('zsír','gramm'),
('paradicsom','darab'),
('paprika','darab'),
('fűszerpaprika','evőkanál'),
('sertés comb','gramm'),
('barack lekvár','gramm'),
('burgonya','gramm'),
('kockatészta','gramm');


-- etelek tábla adatai
insert into etelek(nev,leiras,elkeszitesiido,besorolas) values
('Paradicsomleves','Az olajon megpíritjuk a lisztet. Hozzáadjuk a paradicsompürét, majd felöntjük vízzel és a paradicsomlével. Hozzáadjuk a sót, cukrot, borsot. Külön vízben megfőzzük a betűtésztát. Ha a leves felforrt hozzáadjuk a megfőtt tésztát.',20,'l'),
('Zöldborsóleves','Olajon megpároljuk a zöldborsót, a sárga- és fehérrépát, zellert és az apróra vágott petrezselyemmel. Sóval és borssal fűszerezzük. Meghintjük a liszttel majd felöntjük a vízzel. Ízlés szerint lehet bele galuskát szaggatni, vagy tésztát főzni.',30,'l'),
('Zöldborsófőzelék','Olajon megpároljuk a zöldborsót a petrezselyemmel. Fűszerezzük a cukorral és a sóval. Ha megpuhult a borsó hozzákeverjük a lisztet. Felöntjük a tejjel és a vízzel. Folyamatos kevergetés mellett besűrítjük.',30,'f'),
('Tejberizs','Rizset feltesszük a vízzel főni, ha elfőtte a vizet, akkor felüntjük a tejjel. Hozzáadjuk a cukrot és a vaníliás cukrot. Ha jól felforrt a tűzről levesszük, hozzákeverjük a vajat, majd hagyjuk, hogy a rízs meszívja magát.',25,'é'),
('Tavaszi rizseshús','Az olajon a hagymát megdinszteljük, majd a kockára vágott csirkemellet hozzáadjuk. Ha a csirkemell megpuhult hozzáadjuk a mexikói zöldségköretet, a sót és borsot. Pár perc múlva hozzáadjuka rizst és a vizet, majd addig főzzük, míg a rizs megpuhul.',45,'k'),
('Madártej','A tojásfehérjéket kemény habbá verjük, majd a vaníliás cukorral ízesitett forró tejbe evőkanálla beleszaggatjuk és megfőzzük. A tojássárgákat a cukorral és a liszttel összekeverjük és a habfőzésből visszamaradt tejbe keverjük és folyamatos keverés mellett felforraljuk. A végén hozzáadjuk a habgaluskákat.',50,'é'),
('Sertés pörkölt','A hagymát zsíron megdinszteljük. Hozzáadjuk a felaprított paprikát és paradicsomot, ha megpuhult hozzáadjuk a sertéscombot és puhára főzzük. Hozzáadjuk a fűszereket majd pár percig főzzük.',70,'k'),
('Piskótatekercs','A tojásfehérjéket felverjük, ha kemény hozzáadjuk a cukrot és a sárgáját. Fakanállal beleforgatjuk a lisztet, majd 180 fokos sütőben megsütjük, ha kész konyharuhába feltekerve kihűtjük. Megkenjük a baracklekvárral és feltekerjük.',60,'é'),
('Finomfőzelék','Olajon megpároljuk a zöldborsót, a kockára vágott répát és az aprított petrezselymet. Hozzákeverjük a lisztet majd a tejet, vizet, sót, cukrot. Folyamatos keverés mellett besűrítjük.',35,'f'),
('Krumplistészta','Zsíron megdinszteljük a hagymát, majd hozzáadjuk a fűszerpaprikát, sót, borsot. Belekeverjük a kiskockára vágott főtt burgonyát és a főtt tésztát.',50,'k');


-- hozzavalok tábla adatai
insert into hozzavalok(etelid,anyagid,mennyiseg) values
(1,1,10),
(1,2,1000),
(1,3,50),
(1,4,10),
(1,5,2),
(1,6,5),
(1,7,1),
(1,8,500),
(1,9,100),
(2,1,10),
(2,10,500),
(2,11,2),
(2,12,1),
(2,13,50),
(2,14,1),
(2,4,10),
(2,5,2),
(2,7,1),
(2,9,1500),
(3,1,10),
(3,10,800),
(3,14,1),
(3,4,30),
(3,5,1),
(3,6,20),
(3,15,500),
(3,8,500),
(4,16,150),
(4,15,500),
(4,8,200),
(4,6,80),
(4,18,20),
(4,17,1),
(5,21,3),
(5,22,500),
(5,23,500),
(5,5,3),
(5,7,2),
(5,16,250),
(5,8,500),
(6,24,5),
(6,15,1000),
(6,6,100),
(6,17,3),
(6,4,50),
(7,25,100),
(7,26,1),
(7,27,1),
(7,29,1000),
(7,5,3),
(7,7,2),
(7,28,2),
(8,24,6),
(8,6,60),
(8,4,50),
(8,30,100),
(9,10,300),
(9,11,4),
(9,1,10),
(9,4,20),
(9,15,500),
(9,8,500),
(9,5,1),
(9,6,50),
(9,15,1),
(10,25,100),
(10,21,5),
(10,31,1000),
(10,32,500),
(10,5,3),
(10,7,2),
(10,28,2);